# Generated by Django 5.0.7 on 2025-03-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_paymentgateway_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexplan',
            name='capital_insurance',
            field=models.IntegerField(blank=True, help_text='Capital Insurance percentage', null=True),
        ),
        migrations.AddField(
            model_name='forexplan',
            name='commission',
            field=models.IntegerField(blank=True, help_text='Commission percentage', null=True),
        ),
        migrations.AlterField(
            model_name='forexplan',
            name='duration',
            field=models.CharField(blank=True, default='24hours', help_text='Return period', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='forexplan',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set to null for unlimited (Diamond plan)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='forexplan',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='forexplan',
            name='name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='forexplan',
            name='percentage',
            field=models.IntegerField(help_text='Return percentage within 24 hours'),
        ),
    ]
