# Generated by Django 5.0.7 on 2025-03-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_forexplan_capital_insurance_forexplan_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_investment',
            name='daily_income',
        ),
        migrations.RemoveField(
            model_name='users_investment',
            name='title',
        ),
        migrations.AddField(
            model_name='users_investment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='accounts.forexplan'),
        ),
    ]
