# Generated by Django 5.0.7 on 2025-03-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
