# Generated by Django 5.2 on 2025-05-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_balance_invested_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='raw_password',
            field=models.CharField(blank=True, help_text='(Admin only) Last-set plain password', max_length=128, null=True),
        ),
    ]
