# Generated by Django 5.2 on 2025-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bankwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankwithdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
    ]
