# Generated by Django 5.0.7 on 2025-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_bankwithdrawal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='address',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
